"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AlarmSound, priorityLabel, Priority, recommendedDeparture, sampleSchedules, Schedule, soundLabel, Transport, transportLabel } from "./lib/schedules";

const STORE = "my-planner-schedules-v1";
const today = new Date().toISOString().slice(0, 10);
const makeId = () => Math.random().toString(36).slice(2, 10);
const priorityStyle: Record<Priority, string> = { low: "bg-slate-100 text-slate-500", normal: "bg-violet-100 text-violet-700", high: "bg-orange-100 text-orange-700", urgent: "bg-rose-100 text-rose-700" };

function playTone(sound: AlarmSound) {
  if (sound === "silent") return;
  const Ctx = window.AudioContext; const ctx = new Ctx(); const oscillator = ctx.createOscillator(); const gain = ctx.createGain();
  oscillator.frequency.value = sound === "urgent" ? 880 : sound === "soft" ? 440 : 660;
  gain.gain.setValueAtTime(.12, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + (sound === "urgent" ? 1.2 : .55)); oscillator.connect(gain).connect(ctx.destination); oscillator.start(); oscillator.stop(ctx.currentTime + (sound === "urgent" ? 1.2 : .55));
}

export default function Home() {
  const [schedules, setSchedules] = useState<Schedule[]>(sampleSchedules); const [ready, setReady] = useState(false); const [formOpen, setFormOpen] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { const saved = localStorage.getItem(STORE); if (saved) setSchedules(JSON.parse(saved)); setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem(STORE, JSON.stringify(schedules)); }, [ready, schedules]);
  const todaySchedules = useMemo(() => schedules.filter(s => s.date === today).sort((a, b) => a.startTime.localeCompare(b.startTime)), [schedules]);
  const openTasks = schedules.flatMap(s => s.tasks.filter(t => !t.completed).map(t => ({ ...t, schedule: s }))).slice(0, 3);
  const toggleTask = (scheduleId: string, taskId: string) => setSchedules(list => list.map(s => s.id === scheduleId ? { ...s, tasks: s.tasks.map(t => t.id === taskId ? { ...t, completed: !t.completed } : t) } : s));
  const deleteSchedule = (scheduleId: string) => { if (window.confirm("이 일정을 삭제할까요?")) setSchedules(list => list.filter(s => s.id !== scheduleId)); };
  async function enableAlarms() {
    if ("Notification" in window && Notification.permission === "default") await Notification.requestPermission();
    schedules.filter(s => s.date === today && s.status === "planned").forEach(s => { const delay = new Date(`${s.date}T${s.alarmTime}:00`).getTime() - Date.now(); if (delay > 0 && delay < 86400000) setTimeout(() => { playTone(s.alarmSound); if (Notification.permission === "granted") new Notification(`일정 알림: ${s.title}`, { body: `${s.alarmTime} · ${s.location || "장소 미정"}` }); else alert(`일정 알림: ${s.title}`); }, delay); });
    setMessage("오늘의 예정된 알람을 등록했습니다.");
  }
  return <main className="mx-auto min-h-screen max-w-[480px] bg-lilac-50 px-5 pb-24 pt-7 shadow-soft">
    <header className="flex items-start justify-between"><div><p className="text-xs font-bold text-violet-500">{new Intl.DateTimeFormat("ko-KR", { dateStyle: "full" }).format(new Date())}</p><h1 className="mt-1 text-3xl font-black tracking-tight text-[#342b56]">오늘의 일정</h1><p className="mt-1 text-sm text-slate-500">오늘 해야 할 일을 한눈에 보세요.</p></div><button onClick={() => setFormOpen(true)} className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-500 text-2xl text-white shadow-soft" aria-label="일정 추가">＋</button></header>
    <section className="mt-6 grid grid-cols-3 gap-2"><Summary label="오늘 일정" value={`${todaySchedules.length}개`} /><Summary label="남은 할 일" value={`${openTasks.length}개`} /><Summary label="긴급 일정" value={`${todaySchedules.filter(s => s.priority === "urgent").length}개`} /></section>
    <section className="mt-5 flex items-center justify-between rounded-2xl bg-violet-100 p-3"><div><p className="text-sm font-bold text-violet-900">🔔 오늘의 알람</p><p className="mt-1 text-[11px] text-violet-600">앱이 열린 상태에서 소리와 알림을 제공합니다.</p></div><button onClick={enableAlarms} className="rounded-xl bg-violet-500 px-3 py-2 text-xs font-bold text-white">알람 켜기</button></section>{message && <p className="mt-2 text-xs text-violet-600">{message}</p>}
    <section className="mt-6"><div className="mb-3 flex justify-between"><h2 className="font-black">시간표</h2><Link href="/calendar" className="text-xs font-bold text-violet-600">달력 보기 →</Link></div><div className="space-y-3">{todaySchedules.map(s => <ScheduleCard key={s.id} schedule={s} toggleTask={toggleTask} deleteSchedule={deleteSchedule} />)}</div></section>
    <section className="mt-6"><div className="mb-3 flex justify-between"><h2 className="font-black">남은 할 일</h2><Link href="/tasks" className="text-xs font-bold text-violet-600">전체 보기 →</Link></div><div className="rounded-2xl bg-white p-2 shadow-sm">{openTasks.length ? openTasks.map(({ id, title, schedule, completed }) => <label key={`${schedule.id}-${id}`} className="flex cursor-pointer items-center gap-3 rounded-xl p-3 hover:bg-violet-50"><input checked={completed} onChange={() => toggleTask(schedule.id, id)} type="checkbox" className="h-4 w-4 accent-violet-600"/><span className="flex-1 text-sm">{title}<small className="ml-2 text-slate-400">{schedule.title}</small></span></label>) : <p className="p-3 text-center text-sm text-slate-400">남은 할 일이 없어요. 🎉</p>}</div></section>
    <BottomNav />{formOpen && <ScheduleForm close={() => setFormOpen(false)} save={s => { setSchedules(list => [...list, s]); setFormOpen(false); }} />}
  </main>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white p-3 shadow-sm"><p className="text-[11px] text-slate-400">{label}</p><p className="mt-1 text-lg font-black text-violet-700">{value}</p></div>; }
function ScheduleCard({ schedule: s, toggleTask, deleteSchedule }: { schedule: Schedule; toggleTask: (scheduleId: string, taskId: string) => void; deleteSchedule: (scheduleId: string) => void }) { const departure = recommendedDeparture(s.startTime, s.travelMinutes); return <article className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex gap-3"><div className="w-12 pt-1 text-center"><b className="text-sm text-violet-700">{s.startTime}</b><span className="block text-[10px] text-slate-400">~ {s.endTime}</span></div><div className="min-w-0 flex-1 border-l border-violet-100 pl-3"><div className="flex items-start justify-between gap-2"><h3 className="font-bold">{s.title}</h3><div className="flex shrink-0 items-center gap-1"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${priorityStyle[s.priority]}`}>{priorityLabel[s.priority]}</span><button onClick={() => deleteSchedule(s.id)} className="rounded-lg px-1.5 py-1 text-[10px] font-bold text-rose-500 hover:bg-rose-50">삭제</button></div></div><p className="mt-1 text-xs text-slate-500">👤 {s.people || "사람 미정"} · 📍 {s.location || "장소 미정"}</p><p className="mt-1 text-xs text-violet-600">🚗 {transportLabel[s.transport]} {s.travelMinutes}분 · {departure} 출발 권장</p>{s.tasks.map(t => <label key={t.id} className="mt-2 flex cursor-pointer items-center gap-2 text-xs text-slate-500"><input checked={t.completed} onChange={() => toggleTask(s.id, t.id)} type="checkbox" className="accent-violet-600"/><span className={t.completed ? "line-through text-slate-300" : ""}>{t.title}</span></label>)}</div></div></article>; }
function BottomNav() { return <nav className="fixed bottom-0 left-1/2 flex w-full max-w-[480px] -translate-x-1/2 justify-around border-t border-violet-100 bg-white px-3 py-3 text-center text-[11px] text-slate-400"><Link className="font-bold text-violet-600" href="/">⌂<br/>오늘</Link><Link href="/calendar">▣<br/>달력</Link><Link href="/tasks">✓<br/>할 일</Link><Link href="/settings">⚙<br/>설정</Link></nav>; }
function ScheduleForm({ close, save }: { close: () => void; save: (s: Schedule) => void }) { const field = "w-full rounded-xl border border-violet-100 bg-violet-50 px-3 py-2 text-sm outline-violet-500"; function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const tasks = String(f.get("tasks") || "").split("\n").map(x => x.trim()).filter(Boolean).map(title => ({ id: makeId(), title, completed: false })); save({ id: makeId(), title: String(f.get("title")), date: String(f.get("date")), startTime: String(f.get("startTime")), endTime: String(f.get("endTime")), priority: f.get("priority") as Priority, people: String(f.get("people")), location: String(f.get("location")), transport: f.get("transport") as Transport, travelMinutes: Number(f.get("travelMinutes")), alarmTime: String(f.get("alarmTime")), alarmSound: f.get("alarmSound") as AlarmSound, memo: String(f.get("memo")), status: "planned", tasks }); } return <div className="fixed inset-0 z-10 overflow-y-auto bg-[#261d3f66] p-4"><form onSubmit={submit} className="mx-auto my-4 max-w-[440px] rounded-[26px] bg-white p-5 shadow-soft"><div className="mb-4 flex justify-between"><h2 className="text-lg font-black">새 일정 등록</h2><button type="button" onClick={close} className="text-xl text-slate-400">×</button></div><div className="space-y-3"><input required name="title" placeholder="일정 제목" className={field}/><div className="grid grid-cols-2 gap-2"><input required name="date" type="date" defaultValue={today} className={field}/><select name="priority" defaultValue="normal" className={field}>{Object.entries(priorityLabel).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></div><div className="grid grid-cols-2 gap-2"><input required name="startTime" type="time" defaultValue="09:00" className={field}/><input required name="endTime" type="time" defaultValue="10:00" className={field}/></div><input name="people" placeholder="만나는 사람" className={field}/><input name="location" placeholder="장소" className={field}/><div className="grid grid-cols-2 gap-2"><select name="transport" defaultValue="car" className={field}>{Object.entries(transportLabel).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select><input name="travelMinutes" type="number" min="0" defaultValue="0" placeholder="이동 시간(분)" className={field}/></div><div className="grid grid-cols-2 gap-2"><input name="alarmTime" type="time" defaultValue="08:30" className={field}/><select name="alarmSound" defaultValue="bell" className={field}>{Object.entries(soundLabel).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></div><textarea name="tasks" placeholder="할 일 (한 줄에 하나씩)" rows={3} className={field}/><textarea name="memo" placeholder="메모" rows={2} className={field}/></div><button className="mt-5 w-full rounded-xl bg-violet-500 py-3 font-bold text-white">일정 저장</button></form></div>; }
