"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { Contact } from "../lib/contacts";

const blank = (): Contact => ({ id: "", name: "", phone: "", email: "", company: "", position: "", address: "", memo: "" });
export default function ContactsPage() { const [contacts, setContacts] = useState<Contact[]>([]); const [editing, setEditing] = useState<Contact | null>(null); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [userReady, setUserReady] = useState(false);
  async function load() { const { data, error } = await supabase.from("contacts").select("*").order("name"); if (error) setMessage(error.message); else setContacts(data as Contact[]); }
  useEffect(() => { supabase.auth.getUser().then(({ data }) => { setUserReady(true); if (data.user) load(); }); }, []);
  const visible = useMemo(() => contacts.filter(c => `${c.name} ${c.company} ${c.phone} ${c.email}`.toLowerCase().includes(query.toLowerCase())), [contacts, query]);
  async function remove(id: string) { if (!window.confirm("이 명함을 삭제할까요?")) return; const { error } = await supabase.from("contacts").delete().eq("id", id); if (error) return setMessage(error.message); setContacts(list => list.filter(c => c.id !== id)); }
  return <main className="mx-auto min-h-screen max-w-[480px] bg-lilac-50 p-5 pb-10"><Link href="/" className="text-sm font-bold text-violet-600">← 오늘</Link><div className="mt-4 flex items-center justify-between"><div><h1 className="text-2xl font-black">명함·연락처</h1><p className="mt-1 text-sm text-slate-500">만나는 사람의 정보를 저장하세요.</p></div><button onClick={() => setEditing(blank())} className="grid h-11 w-11 place-items-center rounded-2xl bg-violet-500 text-2xl text-white">＋</button></div>{userReady && !contacts.length && !message && <p className="mt-6 rounded-2xl bg-white p-5 text-center text-sm text-slate-400">로그인 후 명함을 등록할 수 있습니다.</p>}<input value={query} onChange={e => setQuery(e.target.value)} placeholder="이름, 회사, 전화번호 검색" className="mt-5 w-full rounded-xl border border-violet-100 bg-white px-3 py-3 text-sm outline-violet-500"/><div className="mt-3 space-y-2">{visible.map(c => <article key={c.id} className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex justify-between gap-2"><div><h2 className="font-black">{c.name}</h2><p className="mt-1 text-xs text-slate-500">{[c.company, c.position].filter(Boolean).join(" · ") || "소속 정보 없음"}</p></div><div className="flex gap-1"><button onClick={() => setEditing(c)} className="text-xs font-bold text-violet-600">수정</button><button onClick={() => remove(c.id)} className="text-xs font-bold text-rose-500">삭제</button></div></div>{c.phone && <a href={`tel:${c.phone}`} className="mt-3 block text-sm text-violet-700">📞 {c.phone}</a>}{c.email && <a href={`mailto:${c.email}`} className="mt-1 block text-sm text-violet-700">✉ {c.email}</a>}{c.address && <p className="mt-1 text-xs text-slate-500">📍 {c.address}</p>}</article>)}</div>{editing && <ContactForm contact={editing} close={() => setEditing(null)} save={async contact => { const row = { name: contact.name, phone: contact.phone, email: contact.email, company: contact.company, position: contact.position, address: contact.address, memo: contact.memo }; const { data, error } = contact.id ? await supabase.from("contacts").update(row).eq("id", contact.id).select().single() : await supabase.from("contacts").insert(row).select().single(); if (error) return setMessage(error.message); setContacts(list => contact.id ? list.map(c => c.id === contact.id ? data as Contact : c) : [...list, data as Contact]); setEditing(null); }} />}{message && <p className="mt-3 text-xs text-rose-500">{message}</p>}</main>; }
function ContactForm({ contact, close, save }: { contact: Contact; close: () => void; save: (contact: Contact) => void }) { const [value, setValue] = useState(contact); const field = "w-full rounded-xl border border-violet-100 bg-violet-50 px-3 py-2 text-sm outline-violet-500"; const change = (key: keyof Contact, v: string) => setValue(current => ({ ...current, [key]: v })); const submit = (e: FormEvent) => { e.preventDefault(); if (!value.name.trim()) return; save(value); }; return <div className="fixed inset-0 z-20 overflow-y-auto bg-[#261d3f66] p-4"><form onSubmit={submit} className="mx-auto my-5 max-w-[440px] rounded-[26px] bg-white p-5 shadow-soft"><div className="mb-4 flex justify-between"><h2 className="text-lg font-black">{contact.id ? "명함 수정" : "새 명함"}</h2><button type="button" onClick={close} className="text-xl text-slate-400">×</button></div><div className="space-y-3"><input required value={value.name} onChange={e => change("name", e.target.value)} placeholder="이름" className={field}/><input value={value.phone} onChange={e => change("phone", e.target.value)} placeholder="전화번호" className={field}/><input value={value.email} onChange={e => change("email", e.target.value)} type="email" placeholder="이메일" className={field}/><div className="grid grid-cols-2 gap-2"><input value={value.company} onChange={e => change("company", e.target.value)} placeholder="회사명" className={field}/><input value={value.position} onChange={e => change("position", e.target.value)} placeholder="직책" className={field}/></div><input value={value.address} onChange={e => change("address", e.target.value)} placeholder="주소" className={field}/><textarea value={value.memo} onChange={e => change("memo", e.target.value)} placeholder="메모" rows={3} className={field}/></div><button className="mt-5 w-full rounded-xl bg-violet-500 py-3 font-bold text-white">명함 저장</button></form></div>; }
